local M = {}

M.MAP_TILE_WIDTH = 25
M.MAP_TILE_HEIGHT = 0
M.TILE_PX_WIDTH = 32
M.TILE_PX_HEIGHT = 32
M.MAP_PX_WIDTH = M.TILE_PX_WIDTH * M.MAP_TILE_WIDTH
M.MAP_PX_HEIGHT = 0


M.ENEMY_SPEED = 70
M.ENEMY_FIRE_RATE = 0.3
M.ENEMY_PROB_FIRE = 0.05
M.ENEMY_ACCURACY = 0.7 -- higher = worse accuracy

M.PLAYER_SPEED = 120


M.SCROLL_LIMIT = 350

return M